### ISSUE TITLE
Did you have implemented this IP

### ISSUE THREAD

**Issue by Felix-fz** [ysnkhll/BT.656-to-AXI4S-video-decoder#1]
Hi，
  I'm very sorry to interrupt you! I am implementing this IP these days, but I met some problems. Can you open this source code of this project? Thank you! Looking forward for you.🤕🤕🤕

**Comment by ysnkhll** [comment]
> Hi， I'm very sorry to interrupt you! I am implementing this IP these days, but I met some problems. Can you open this source code of this project? Thank you! Looking forward for you.🤕🤕🤕

There are legal reasons why I never uploaded the source. I actually completely forgot about this repository. I plan to re-implement this using a different approach/methodology to avoid any similarities to my original work on this IP for a company which I will not name. I can't give any estimates when that will be. However, I can offer a little guidance and advice. 

I actually followed the ITU spec very closely which you can download for free from [here](https://www.itu.int/rec/R-REC-BT.656-3-199510-S/en). Also, Xilinx's [Framebuffer product guide](https://docs.xilinx.com/v/u/2.1-English/pg278-v-frmbuf) was super helpful. You should be able to implement this relatively quickly with those two documents. You simply just need to setup 4 or 5 registers for the input data so you can properly parse the stream and determine how to format it for the Framebuffer.

Good luck!
